//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureMVCTruck.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AzureMVCDeployementEntities : DbContext
    {
        public AzureMVCDeployementEntities()
            : base("name=AzureMVCDeployementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TruckDetail> TruckDetails { get; set; }
        public virtual DbSet<TruckRefBrand> TruckRefBrands { get; set; }
    }
}
